export * from './accessGroup.service';
import { AccessGroupService } from './accessGroup.service';
export * from './account.service';
import { AccountService } from './account.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './company.service';
import { CompanyService } from './company.service';
export * from './controller.service';
import { ControllerService } from './controller.service';
export * from './department.service';
import { DepartmentService } from './department.service';
export * from './door.service';
import { DoorService } from './door.service';
export * from './holiday.service';
import { HolidayService } from './holiday.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './schedule.service';
import { ScheduleService } from './schedule.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './zone.service';
import { ZoneService } from './zone.service';
export const APIS = [AccessGroupService, AccountService, AuthService, CompanyService, ControllerService, DepartmentService, DoorService, HolidayService, LocationService, ScheduleService, UsersService, ZoneService];
