/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessGroupScheduleZone } from './accessGroupScheduleZone';
import { LocationResponse } from './locationResponse';

export interface AccessGroupResponse { 
    readonly id: number;
    readonly name: string;
    readonly updatedAt: Date;
    location: LocationResponse;
    readonly users: number;
    zoneSchedules: Array<AccessGroupScheduleZone>;
}