/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessGroup } from './accessGroup';

export interface AccessGroupPerLocation { 
    locationId: number;
    locationName: string;
    accessGroups: Array<AccessGroup>;
}