/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';

export interface AccountResponse { 
    fullName: string;
    profilePicture: string;
    jobTitle: string;
    company: Company;
    city: string;
    country: string;
    email: string;
    phoneNumber: string;
    twoStepAuth: boolean;
}