/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeControllerStatus } from './typeControllerStatus';

export interface ControllerResponse { 
    id: number;
    name: string;
    status: TypeControllerStatus;
    updatedAt: Date;
    location: string;
    doors: number;
}