/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssignLocationDto } from './assignLocationDto';
import { CreateCardDto } from './createCardDto';
import { TypeTierAdminOption } from './typeTierAdminOption';
import { TypeUserRole } from './typeUserRole';

export interface CreateUserDto { 
    email: string;
    fullName: string;
    phoneNumber: string;
    companyId: number;
    role: TypeUserRole;
    roleOption?: TypeTierAdminOption;
    allowSso?: boolean;
    locations: Array<AssignLocationDto>;
    cards?: Array<CreateCardDto>;
    instantlyInvite: boolean;
}