/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateCustomAccessDto } from './createCustomAccessDto';
import { LinkScheduleZoneDto } from './linkScheduleZoneDto';

export interface CreateAccessGroupDto { 
    name: string;
    locationId: number;
    zoneSchedules: Array<LinkScheduleZoneDto>;
    custom?: Array<CreateCustomAccessDto>;
}