/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeDoorStatus } from './typeDoorStatus';

export interface Door { 
    id: number;
    name: string;
    status: TypeDoorStatus;
    updatedAt: Date;
}