/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeslotResponse } from './timeslotResponse';

export interface HolidayDescription { 
    id: number;
    name: string;
    isActive: boolean;
    timetables: Array<TimeslotResponse>;
}