/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HolidayDescription } from './holidayDescription';
import { TimetableResponse } from './timetableResponse';

export interface ScheduleDescription { 
    id: number;
    name: string;
    description: string;
    updatedAt: Date;
    holidays: Array<HolidayDescription>;
    timetables: Array<TimetableResponse>;
}