/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeControllerStatus = 'PENDING' | 'PAIRED' | 'NO_SIGNAL';

export const TypeControllerStatus = {
    PENDING: 'PENDING' as TypeControllerStatus,
    PAIRED: 'PAIRED' as TypeControllerStatus,
    NOSIGNAL: 'NO_SIGNAL' as TypeControllerStatus
};