/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeRole = 'GUEST' | 'MEMBER' | 'SECURITY' | 'USER_MANAGER' | 'FRONT_DESK' | 'ADMIN' | 'SUPER_ADMIN';

export const TypeRole = {
    GUEST: 'GUEST' as TypeRole,
    MEMBER: 'MEMBER' as TypeRole,
    SECURITY: 'SECURITY' as TypeRole,
    USERMANAGER: 'USER_MANAGER' as TypeRole,
    FRONTDESK: 'FRONT_DESK' as TypeRole,
    ADMIN: 'ADMIN' as TypeRole,
    SUPERADMIN: 'SUPER_ADMIN' as TypeRole
};