/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeDayOfWeek = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY';

export const TypeDayOfWeek = {
    MONDAY: 'MONDAY' as TypeDayOfWeek,
    TUESDAY: 'TUESDAY' as TypeDayOfWeek,
    WEDNESDAY: 'WEDNESDAY' as TypeDayOfWeek,
    THURSDAY: 'THURSDAY' as TypeDayOfWeek,
    FRIDAY: 'FRIDAY' as TypeDayOfWeek,
    SATURDAY: 'SATURDAY' as TypeDayOfWeek,
    SUNDAY: 'SUNDAY' as TypeDayOfWeek
};