/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeHolidayRecurrence = 'ONCE' | 'EVERY_MONTH' | 'EVERY_YEAR';

export const TypeHolidayRecurrence = {
    ONCE: 'ONCE' as TypeHolidayRecurrence,
    EVERYMONTH: 'EVERY_MONTH' as TypeHolidayRecurrence,
    EVERYYEAR: 'EVERY_YEAR' as TypeHolidayRecurrence
};