/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeUserRoleOutput = 'GUEST' | 'MEMBER' | 'TIER_ADMIN' | 'ADMIN' | 'SUPER_ADMIN';

export const TypeUserRoleOutput = {
    GUEST: 'GUEST' as TypeUserRoleOutput,
    MEMBER: 'MEMBER' as TypeUserRoleOutput,
    TIERADMIN: 'TIER_ADMIN' as TypeUserRoleOutput,
    ADMIN: 'ADMIN' as TypeUserRoleOutput,
    SUPERADMIN: 'SUPER_ADMIN' as TypeUserRoleOutput
};