/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeFilterRole = 'ADMIN' | 'TIER_ADMIN' | 'GUEST';

export const TypeFilterRole = {
    ADMIN: 'ADMIN' as TypeFilterRole,
    TIERADMIN: 'TIER_ADMIN' as TypeFilterRole,
    GUEST: 'GUEST' as TypeFilterRole
};