/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeRole = 'GUEST' | 'MEMBER' | 'TIER_ADMIN' | 'ADMIN';

export const TypeRole = {
    GUEST: 'GUEST' as TypeRole,
    MEMBER: 'MEMBER' as TypeRole,
    TIERADMIN: 'TIER_ADMIN' as TypeRole,
    ADMIN: 'ADMIN' as TypeRole
};