/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeUserStatus = 'PENDING' | 'INCOMPLETE' | 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';

export const TypeUserStatus = {
    PENDING: 'PENDING' as TypeUserStatus,
    INCOMPLETE: 'INCOMPLETE' as TypeUserStatus,
    ACTIVE: 'ACTIVE' as TypeUserStatus,
    INACTIVE: 'INACTIVE' as TypeUserStatus,
    ARCHIVED: 'ARCHIVED' as TypeUserStatus
};