/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeTierAdminOption = 'SECURITY' | 'USER_MANAGER' | 'FRONT_DESK';

export const TypeTierAdminOption = {
    SECURITY: 'SECURITY' as TypeTierAdminOption,
    USERMANAGER: 'USER_MANAGER' as TypeTierAdminOption,
    FRONTDESK: 'FRONT_DESK' as TypeTierAdminOption
};