/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TypeDoorStatus = 'PENDING' | 'NOT_PAIRED' | 'PAIRED';

export const TypeDoorStatus = {
    PENDING: 'PENDING' as TypeDoorStatus,
    NOTPAIRED: 'NOT_PAIRED' as TypeDoorStatus,
    PAIRED: 'PAIRED' as TypeDoorStatus
};