/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UpdateScheduleHolidayDto } from './updateScheduleHolidayDto';
import { UpdateTimetableDto } from './updateTimetableDto';

export interface UpdateDoorDto { 
    id: number;
    name?: string;
    timetables?: Array<UpdateTimetableDto>;
    holidays?: Array<UpdateScheduleHolidayDto>;
}