/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TypeTierAdminOption } from './typeTierAdminOption';
import { TypeUserRole } from './typeUserRole';
import { UserStatusForUpdate } from './userStatusForUpdate';

export interface UpdateUserDto { 
    id: number;
    profilePicture?: string;
    fullName?: string;
    email?: string;
    status?: UserStatusForUpdate;
    role?: TypeUserRole;
    roleOption?: TypeTierAdminOption;
    phoneNumber?: string;
    companyId?: number;
    employeeNumber?: number;
    departmentId?: number;
    costCenterId?: number;
}