/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AccessGroupInfo } from './accessGroupInfo';
import { CardResponse } from './cardResponse';
import { Company } from './company';
import { DepartmentResponse } from './departmentResponse';
import { TypeUserRole } from './typeUserRole';
import { TypeUserStatus } from './typeUserStatus';

export interface UserInfo { 
    id: number;
    fullName: string;
    email: string;
    profilePicture: string;
    roles: Array<TypeUserRole>;
    status: TypeUserStatus;
    phoneNumber: string;
    company: Company;
    createdAt: Date;
    updatedAt: Date;
    updatedBy: string;
    department: DepartmentResponse;
    costCenter: DepartmentResponse;
    employeeNumber: number;
    accessGroups: Array<AccessGroupInfo>;
    cards: Array<CardResponse>;
}