/**
 * Invicto API
 * REST API Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { Department } from './department';
import { TypeRole } from './typeRole';
import { TypeUserStatus } from './typeUserStatus';

export interface User { 
    id: number;
    fullName: string;
    phoneNumber: string;
    email: string;
    profilePicture?: string;
    jobTitle?: string;
    costCenter?: Department;
    department?: Department;
    city?: string;
    country?: string;
    allowSso?: boolean;
    status: TypeUserStatus;
    roles: Array<TypeRole>;
    lastActivity: Date;
    twoStepAuth: any;
    permissions: any;
    company: Company;
}